sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u Y4W7ArwRVw1s7bXX6yH/ztFKwY0IVG7zvqwfSE2oN2ESpeED9YhlBIVvh2UYbIJF339EcuRqMyEgB5+x5FDr9cgKQ9ooopjfv2QYeYVGHCsYwU0oyTYy43UDIbgZTjoEi2xilwLShyvlpRneZDRCylkUErIXjS98gPk9hdJQ+8RFChgi20dcnNE5wpgFviqpUpZQY4WdNqqMHmD6YO+9tC4pmmDAQrMGX41Et9Iud0h9ZcbJ6r3Uq8xG8nH/+n9wJGH5N0aW3H9zXSOjPh9hdqnKce9JL7UpWiy+MMzPO9HDMle6h7oOFuXvCevQ0b3pxQAG8uuhSJmM7fX8+qwveVThHSoOtTT0yQ7+L460oS4kH7CddH7pAdT/Gv7uBq60dMBUBCIwg7mZ5o1NI57E8H6UXNgH/tBE4YdLYOuZ/Y8Dm8TxomvB/1BAcnb+O6Vaf8Shb8oX99arO7pVa3zCBqCR/4GhbPlIiabMcACoxy1QPlQEnndlXoL1OtJHK/NdY4X5n0Zd6Tj/PVdbbpv02dzS1n0kJERnhJVf+XnQqGyWb43MPdITnS+6JA5twrlo3h/G09PShis0TKyHwAANEUJnRbjQfD1AMMSZl6ia1su20uJQbnS4AAAKXg//hLyVe3BtyouDGmN87M/rQGNBl8VGrtpD2JzKOlEghlwFeEQ= -p qVpt8+/oDUUEn3CxaUB72HoA9P6PGXhc8sETgWK9Hh30rQq8pECxaMifD+ykdkBOaO5cXi3HLslaAu/4m58cChDnr3gtbX551DVYxtV/sy28i0hjX0KOco26fjiPKsDy3GPAhzGxb2ZaME5rmn6fXdXfD6sg6lcRkTIX4wzT2bOZw8ilkIHmS+9d7mt6mmG56wqd2WV7yfvUL0yUnojtlbqhUlcKlPWGGUVLsLNXJK4TvDF1lEW72PCV1D7Y8WSeoPq7jU81DOlGqHxrBrpZOOnEGAFbNYB7/RGsWqXd/GOz6helLcdQfxym/ZupGonyJSZQ1ATe7EchQwhHHZC1z1US0uXkGEm18InQ/CtnxU5oVqh2kB7J3NBdzeWoReMKvDZaN7LwHsvVU7ZK79qUkFhrKhd2nUFgQZFUHrZvYXjAUq3LLemIfjhr9iJ3CT5UEyY6VgFZjwVw8V7irdFpYsSENMiBA88HUxzNn07Oac4D4VdOEi6DQwnYjjI/0BKm4vXkgivjdhHm02kr2UxInkCTXZHCQ+QLbpwfChF3lLX+nj0vvWOfrS873HzBG2CziLy22rb+UiwMD1sjmSkUOvssxsY2ZUYazEx+DhLOZytk60ZAJB7aitPiwZqt5PnTtsPXV8AxtSNMu4mPMY0TOqJYfNkcXpDHuTySVeYk8so
- docker tag swagger-spring-example:1.0.0 gwnbjorn1/devops_individual_assignment
- docker push gwnbjorn1/devops_individual_assignment
env:
  global:
  - secure: Y4W7ArwRVw1s7bXX6yH/ztFKwY0IVG7zvqwfSE2oN2ESpeED9YhlBIVvh2UYbIJF339EcuRqMyEgB5+x5FDr9cgKQ9ooopjfv2QYeYVGHCsYwU0oyTYy43UDIbgZTjoEi2xilwLShyvlpRneZDRCylkUErIXjS98gPk9hdJQ+8RFChgi20dcnNE5wpgFviqpUpZQY4WdNqqMHmD6YO+9tC4pmmDAQrMGX41Et9Iud0h9ZcbJ6r3Uq8xG8nH/+n9wJGH5N0aW3H9zXSOjPh9hdqnKce9JL7UpWiy+MMzPO9HDMle6h7oOFuXvCevQ0b3pxQAG8uuhSJmM7fX8+qwveVThHSoOtTT0yQ7+L460oS4kH7CddH7pAdT/Gv7uBq60dMBUBCIwg7mZ5o1NI57E8H6UXNgH/tBE4YdLYOuZ/Y8Dm8TxomvB/1BAcnb+O6Vaf8Shb8oX99arO7pVa3zCBqCR/4GhbPlIiabMcACoxy1QPlQEnndlXoL1OtJHK/NdY4X5n0Zd6Tj/PVdbbpv02dzS1n0kJERnhJVf+XnQqGyWb43MPdITnS+6JA5twrlo3h/G09PShis0TKyHwAANEUJnRbjQfD1AMMSZl6ia1su20uJQbnS4AAAKXg//hLyVe3BtyouDGmN87M/rQGNBl8VGrtpD2JzKOlEghlwFeEQ=
  - secure: qVpt8+/oDUUEn3CxaUB72HoA9P6PGXhc8sETgWK9Hh30rQq8pECxaMifD+ykdkBOaO5cXi3HLslaAu/4m58cChDnr3gtbX551DVYxtV/sy28i0hjX0KOco26fjiPKsDy3GPAhzGxb2ZaME5rmn6fXdXfD6sg6lcRkTIX4wzT2bOZw8ilkIHmS+9d7mt6mmG56wqd2WV7yfvUL0yUnojtlbqhUlcKlPWGGUVLsLNXJK4TvDF1lEW72PCV1D7Y8WSeoPq7jU81DOlGqHxrBrpZOOnEGAFbNYB7/RGsWqXd/GOz6helLcdQfxym/ZupGonyJSZQ1ATe7EchQwhHHZC1z1US0uXkGEm18InQ/CtnxU5oVqh2kB7J3NBdzeWoReMKvDZaN7LwHsvVU7ZK79qUkFhrKhd2nUFgQZFUHrZvYXjAUq3LLemIfjhr9iJ3CT5UEyY6VgFZjwVw8V7irdFpYsSENMiBA88HUxzNn07Oac4D4VdOEi6DQwnYjjI/0BKm4vXkgivjdhHm02kr2UxInkCTXZHCQ+QLbpwfChF3lLX+nj0vvWOfrS873HzBG2CziLy22rb+UiwMD1sjmSkUOvssxsY2ZUYazEx+DhLOZytk60ZAJB7aitPiwZqt5PnTtsPXV8AxtSNMu4mPMY0TOqJYfNkcXpDHuTySVeYk8so=