sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- nvm install --lts
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag swagger-spring-example:1.0.0 gwnbjorn1/devops_individual_assignment
- docker push gwnbjorn1/devops_individual_assignment
env:
  global:
  - secure: kNS5nOIiyQr5ob7EDBml+9KmHX4h0mBo7ICrCYXHdo98DrxiJahf687g6mWqMF4dyzTwDV88SZLZlSB6KrYXrCPzuUQnN7C1t989N5eCSWY1NU66KK815kHfjgRBLbp+9fp4uopwWI52jH7DMdIe36tUwwa8fWYIeqQ4z2UhoiLrZRSCp8kBpTfnT47KGrNX8KBZ3TFtoL/B04YKiE84AeNct3rzC+gVAfvkh8SJt9pSwLzoDX3D+oyOgkvJVw9/1QuiRMnUq1OIvRF/rWSF6rQsT4G3ID0oOJOps/PV748vDCrBgVkCMa81z37/FIIvdth6OAgETER8E+fRQWP7e5Ok7G/j4l7CyGUD+uuWBqxUaufT9Alaq5QOrxJZqQSUpg6pgbyQJJknHZG3nUI7vk8yzqggjzpAy5E0qFKRA94QxnmROMjvaG4RDBAjkOvbovEPnTUz45HBHPwIsSHWEUC0D0DztLNW9DpeeFuozsdABL7TMl4V8FySFKNJbEgcOZHQ6YtKaoARlcQ5caOgvYduscESyLdDg5gfhKmShGahwJf6NECZ8ffSeqYUqr7fErDNN1QlW3ZNVfD2S5XzSDHFxygLhxTloeLPulpsppHcyaatkFSHo4bHh4dyguMTVpEVDrAMOSw2eyaSyY9G15CMLZc+5xhS5FvBrzd1W0s=
  - secure: CGl3ccwHYxlYPMVxW6LxmMXHRMf2c6Tl9Ef0nawVGtNOmexXslwDzBVUuO6va4OTPXj68NmfaCDLOwDRHQCW0dUaJMPDSOlih24EW2tegW6psY8kfv8BimTSPDEBA6gDOqH0od3SHgwp03IMJpEP8dtkxzOAZRh7NRsiYfUykY5Ms3rl3u4wX/9OG61DPeWNDt/ZMJfZJnXsrMSUPc+Yz1IPe6v8XgtxiXjVhXE/ALW+NSPuxIwb4ZWkqiL5uK/dHa1gMth3YPTdy9LXyAT0wkCTxpc4Hmf0ZWEeBoi+pwz/k1aZHJX/RhyJHatRUG0Z47XDLNQrz43mAZ0tz8UlSTH0KonSMOpc1rmnMRDjnOCBLMxIQvuqYZ2mKoPru4E/dB3MkPSl29ZVlgU3eUXZFlOUgr+nyFV8woOowORzhKfEmE5c6pUzAS1VxCfD2No+c8+1mbQc3OnJ/26HUCjVhI9nBNkDgavxVWJoPk/f7BhPf7XO6Tb1uoC0AewuRytTOxBpd9MCyMv/sSrqFxBBvsoCrujszXpGWZeW6YlGfvlH6NlRiB6P9ExmLEYhKTS12mcUyBTkaWgl35uSmhgCzB1M7eEtngccyx+KRaY8xb+FaPBWyxVcrAMHQgKlU8ulKNYNQGiNespcbCZtgIs6wlSvFiz0C547VzzpG0WH0eg=
